import {AbsoluteFill,Audio,Composition,Easing,Img,OffthreadVideo,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
import scenes from './data.json';
const C={navy:'#0B203A',cream:'#F5F0E6',red:'#C9333D',gold:'#E6C784',white:'#FFFFFF'};
const ease=(f:number,d=0,len=19)=>interpolate(f,[d,d+len],[0,1],{easing:Easing.bezier(.16,1,.3,1),extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const H={fontFamily:'BC, Arial, sans-serif',fontWeight:750,lineHeight:1.02,letterSpacing:-3} as const;

function Reveal({children,delay=0,size=100,color=C.cream}:any){const f=useCurrentFrame();const p=ease(f,delay);return <div style={{overflow:'hidden',paddingBottom:8}}><div style={{...H,fontSize:size,color,transform:`translateY(${(1-p)*115}%)`,opacity:Math.min(p*3,1)}}>{children}</div></div>}
function Eyebrow({children,delay=0}:any){const f=useCurrentFrame();return <div style={{display:'flex',alignItems:'center',gap:18,fontSize:23,fontWeight:600,letterSpacing:3,opacity:ease(f,delay),marginBottom:24}}><div style={{width:38*ease(f,delay),height:3,background:C.red}}/>{children}</div>}
function Folio({n,label}:any){return <div style={{display:'flex',alignItems:'center',gap:13,fontSize:19,letterSpacing:2,color:C.gold}}><span style={{fontSize:26,fontWeight:700}}>0{n}</span><span style={{width:35,height:1,background:C.gold}}/>{label}</div>}
function Pulse({f,width=540}:any){const path='M0 58H85L101 47L117 58H161L181 24L207 94L234 5L263 65L282 49L304 58H540';return <svg width={width} height={100} viewBox="0 0 540 100" fill="none"><path d={path} stroke={C.cream} strokeOpacity=".12" strokeWidth="2"/><path d={path} pathLength="1" stroke={C.red} strokeWidth="4" strokeDasharray="1" strokeDashoffset={1-ease(f,8,50)} strokeLinecap="round"/></svg>}
function Reticle({f}:any){return <svg width="580" height="400" viewBox="0 0 580 400" fill="none"><path d="M40 95V35H105M475 35H540V95M540 305V365H475M105 365H40V305" stroke={C.gold} strokeWidth="2" strokeDasharray="380" strokeDashoffset={380*(1-ease(f,9,24))}/><path d="M280 200H300M290 190V210" stroke={C.gold} strokeWidth="2"/><circle cx="290" cy="200" r={22+ease(f,12)*18} stroke={C.gold} opacity={.7*(1-ease(f,35,25))}/></svg>}
function Captions({words}:any){const f=useCurrentFrame();const t=f/30;const index=words.reduce((n:number,w:any,j:number)=>t>=w.start?j:n,0);const start=Math.floor(index/4)*4;const group=words.slice(start,start+4);return <div style={{position:'absolute',left:65,right:120,bottom:262,textAlign:'center',fontSize:43,fontWeight:600,lineHeight:1.3,textShadow:'0 2px 10px #000'}}><span style={{padding:'12px 20px',background:'#071420D9',borderRadius:3,boxDecorationBreak:'clone',WebkitBoxDecorationBreak:'clone'}}>{group.map((w:any,j:number)=><span key={j} style={{color:j+start===index?C.gold:C.white}}>{w.text} </span>)}</span></div>}
function Chapter({s,index}:any){const f=useCurrentFrame();const p=ease(f);const last=s.frames;const isVideo=s.bg.endsWith('mp4');const scale=interpolate(f,[0,last],[1.01,1.055]);const step=s.kind==='practice'?(f<54?0:f<105?1:2):0;
 return <AbsoluteFill style={{background:C.navy,overflow:'hidden'}}>
 {isVideo?<OffthreadVideo src={staticFile('authentic/'+s.bg)} startFrom={s.offset*30} muted style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${scale+(step===1?.065:step===2?.02:0)})`,transformOrigin:step===1?'64% 59%':'50% 50%',filter:'contrast(1.065) saturate(.87) brightness(.97)'}}/>:<Img src={staticFile('authentic/facultad.jpg')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${s.kind==='hook'?1.1-.09*ease(f,0,67):1.01+.045*f/last})`,filter:'saturate(.8) contrast(1.06)'}}/>}
 <AbsoluteFill style={{background:'linear-gradient(180deg,rgba(5,19,33,.72),rgba(5,19,33,.03) 43%,rgba(5,19,33,.05) 65%,rgba(5,19,33,.88))'}}/>
 <div style={{position:'absolute',top:72,left:65,display:'flex',alignItems:'center',gap:18}}><div style={{background:C.cream,width:84,height:74,borderRadius:3}}><Img src={staticFile('authentic/logo.png')} style={{width:'100%',height:'100%',objectFit:'contain'}}/></div><div style={{fontSize:19,letterSpacing:2,fontWeight:650}}>BEN CARSON<br/><span style={{fontSize:14,letterSpacing:3,fontWeight:400}}>PREPARATORIA</span></div></div>
 <div style={{position:'absolute',top:89,right:110,fontSize:17,letterSpacing:2}}>COCHABAMBA<br/><span style={{color:C.gold,fontSize:13}}>BOLIVIA / 17°S</span></div>

 {s.kind==='hook'&&<>
 <div style={{position:'absolute',left:65,top:240,right:115}}><Eyebrow>UN FUTURO QUE EMPIEZA HOY</Eyebrow><Reveal size={112}>¿Te imaginas</Reveal><Reveal delay={4} size={128}>entrando</Reveal><Reveal delay={8} size={128} color={C.gold}>aquí?</Reveal></div>
 <div style={{position:'absolute',left:230,top:940,transform:`translateY(${(1-p)*25}px)`}}><Reticle f={f}/></div>
 <div style={{position:'absolute',left:90,top:1320,opacity:ease(f,20)}}><Folio n={1} label="FACULTAD DE MEDICINA"/><div style={{height:1,width:300,background:C.gold,marginTop:18,transform:`scaleX(${ease(f,20)})`,transformOrigin:'left'}}/></div>
 </>}
 {s.kind==='goal'&&<>
 <div style={{position:'absolute',left:65,top:235}}><Eyebrow>UNIVERSIDAD MAYOR DE SAN SIMÓN</Eyebrow><Reveal size={132}>Medicina.</Reveal><Reveal size={59} delay={5} color={C.gold}>Tu próximo capítulo.</Reveal></div>
 <div style={{position:'absolute',left:65,top:610,width:580,height:645,overflow:'hidden',clipPath:`inset(${(1-ease(f,6,24))*100}% 0 0 0)`,boxShadow:'0 25px 60px #0006'}}><Img src={staticFile('authentic/facultad.jpg')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1.12-.12*ease(f,6,45)})`}}/><div style={{position:'absolute',inset:0,border:'1px solid #FFFFFF80'}}/></div>
 <div style={{position:'absolute',left:585,top:775,width:340,height:530,background:C.navy,overflow:'hidden',boxShadow:'0 20px 45px #0005',transform:`translateX(${(1-ease(f,13,26))*110}px)`,opacity:ease(f,13)}}><Img src={staticFile('pro/heart-atlas.png')} style={{width:'100%',height:485,objectFit:'cover',transform:`scale(${1+.018*Math.sin(f/9)})`}}/><div style={{position:'absolute',bottom:0,left:0,right:0,padding:'14px 18px',fontSize:14,letterSpacing:3,background:C.navy,color:C.gold}}>VOCACIÓN · MEDICINA</div></div>
 <div style={{position:'absolute',left:80,top:1300,opacity:ease(f,16)}}><Pulse f={f} width={460}/></div>
 <div style={{position:'absolute',left:700,top:620,display:'flex',alignItems:'center',gap:15,opacity:ease(f,10)}}><Img src={staticFile('authentic/umss.jpg')} style={{width:66,height:85,objectFit:'contain',background:'white'}}/><div style={{fontSize:20,letterSpacing:2}}>META<br/><b>UMSS</b></div></div>
 </>}
 {s.kind==='reality'&&<>
 <div style={{position:'absolute',top:235,left:65,right:115}}><Eyebrow>LA PREPARACIÓN ES EL COMIENZO</Eyebrow><Reveal size={107}>Mucho antes</Reveal><Reveal size={107} delay={4}>del examen.</Reveal></div>
 <div style={{position:'absolute',left:65,top:1210,width:750,borderLeft:`3px solid ${C.red}`,paddingLeft:25,opacity:ease(f,14),transform:`translateY(${24*(1-ease(f,14))}px)`}}><Folio n={2} label="EL TRABAJO DIARIO"/><div style={{fontSize:39,fontWeight:550,marginTop:18}}>Una pregunta más.<br/>Un paso más cerca.</div></div>
 </>}
 {s.kind==='practice'&&<>
 <div style={{position:'absolute',top:240,left:65,right:105}}><Eyebrow>APRENDER TAMBIÉN ES CORREGIR</Eyebrow><div key={step} style={{overflow:'hidden'}}><div style={{...H,fontSize:125,color:C.gold,transform:`translateY(${(1-ease(f,step===0?0:step===1?54:105,12))*110}%)`}}>{['Pregunta.','Practica.','Corrige.'][step]}</div></div></div>
 <div style={{position:'absolute',left:65,top:1000,width:495,height:367,background:C.cream,color:C.navy,boxShadow:'0 18px 45px #0004',transform:`perspective(1200px) rotateY(${(1-ease(f,8))*-12}deg) translateX(${(1-ease(f,8))*-80}px)`,opacity:ease(f,8)}}><div style={{height:5,background:C.red}}/><div style={{padding:'30px 33px'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:15,letterSpacing:2,borderBottom:'1px solid #0B203A33',paddingBottom:19}}><b>CUADERNO DE PRÁCTICA</b><span>BC / 01</span></div>{['Resuelve','Revisa','Vuelve a intentar'].map((x,i)=><div key={x} style={{display:'flex',alignItems:'center',gap:18,marginTop:25,fontSize:29,fontWeight:600}}><svg width="34" height="34" viewBox="0 0 40 40"><rect x="2" y="2" width="32" height="32" fill="none" stroke="#0B203A55"/><path d="M7 19L17 29L33 8" pathLength="1" stroke={C.red} strokeWidth="3" fill="none" strokeDasharray="1" strokeDashoffset={1-ease(f,20+i*48,12)}/></svg>{x}</div>)}</div></div>
 <div style={{position:'absolute',left:700,top:1190,fontSize:98,fontWeight:250,color:C.cream,opacity:ease(f,15),borderBottom:'2px solid '+C.red}}>0{step+1}<span style={{fontSize:24,color:C.gold}}>/03</span></div>
 </>}
 {s.kind==='team'&&<>
 <div style={{position:'absolute',left:65,top:245}}><Eyebrow>COMPARTE EL CAMINO</Eyebrow><Reveal size={112}>La misma</Reveal><Reveal size={129} color={C.gold} delay={4}>meta.</Reveal></div>
 <div style={{position:'absolute',left:65,top:1260,width:650,opacity:ease(f,13)}}><div style={{fontSize:39,lineHeight:1.3,fontWeight:500}}>Gente que también<br/>quiere llegar.</div><svg width="450" height="35" viewBox="0 0 450 35"><path d="M5 23Q190 5 440 20" pathLength="1" fill="none" stroke={C.red} strokeWidth="5" strokeDasharray="1" strokeDashoffset={1-ease(f,15,28)}/></svg></div>
 </>}
 {s.kind==='brand'&&<>
 <div style={{position:'absolute',top:245,left:65}}><Eyebrow>PREPARACIÓN PARA MEDICINA</Eyebrow><Reveal size={92}>Esto es</Reveal><Reveal size={127} delay={4} color={C.gold}>Ben Carson.</Reveal></div>
 <div style={{position:'absolute',left:250,top:860,width:500,height:410,background:C.cream,boxShadow:'0 25px 70px #0006',clipPath:`inset(0 ${(1-ease(f,7,22))*100}% 0 0)`}}><Img src={staticFile('authentic/logo.png')} style={{position:'absolute',left:55,top:5,width:390,height:350,objectFit:'contain'}}/><div style={{position:'absolute',bottom:28,left:45,right:45,display:'flex',gap:13,alignItems:'center',color:C.navy,fontSize:17,letterSpacing:3}}><span style={{width:40,height:2,background:C.red}}/>TU META NOS MUEVE</div></div>
 </>}
 {s.kind==='cta'&&<>
 <AbsoluteFill style={{background:'linear-gradient(0deg,#0B203ADD,transparent 85%)'}}/>
 <div style={{position:'absolute',top:230,left:65,right:110}}><Eyebrow>DA EL SIGUIENTE PASO</Eyebrow><Reveal size={109}>Tu meta:</Reveal><Reveal size={107} delay={4} color={C.gold}>Medicina UMSS.</Reveal></div>
 <div style={{position:'absolute',top:820,left:65,right:125,opacity:ease(f,11),transform:`translateY(${35*(1-ease(f,11))}px)`}}><div style={{height:1,background:'#F5F0E677',transform:`scaleX(${ease(f,11,22)})`,transformOrigin:'left'}}/><div style={{marginTop:40,fontSize:62,fontWeight:650,letterSpacing:-1}}>Hablemos de tu preparación.</div><div style={{fontSize:25,color:C.gold,letterSpacing:3,marginTop:42}}>ESCRÍBENOS</div><div style={{fontSize:60,letterSpacing:1,fontWeight:650,marginTop:18}}>75960539</div><div style={{fontSize:60,letterSpacing:1,fontWeight:650,marginTop:6}}>76998745</div><div style={{display:'flex',alignItems:'center',gap:20,marginTop:35,fontSize:33}}><div style={{height:3,width:55,background:C.red}}/>@prepabencarson</div></div>
 </>}

 <Captions words={s.words}/>
 <div style={{position:'absolute',bottom:175,left:65,right:125,display:'flex',justifyContent:'space-between',fontSize:15,letterSpacing:2,color:C.cream}}><span>BEN CARSON / MEDICINA</span><span>0{index+1} — 07</span></div>
 <div style={{position:'absolute',bottom:150,left:65,right:125,height:1,background:'#FFFFFF33'}}><div style={{height:1,background:C.gold,width:`${100*(index+f/s.frames)/7}%`}}/></div>
 {['goal','brand'].includes(s.kind)&&f<12&&<AbsoluteFill style={{background:C.navy,transform:`translateX(${ease(f,0,12)*110}%)`,borderLeft:'5px solid '+C.red}}/>}
 </AbsoluteFill>
}
function Film(){let from=0;return <AbsoluteFill style={{fontFamily:'BC,Arial,sans-serif',color:C.cream}}><style>{`@font-face{font-family:BC;src:url('${staticFile('pro/brand.ttf')}') format('truetype');font-weight:100 900;}`}</style><Audio src={staticFile('authentic/beat.wav')} volume={.27}/>{scenes.map((s,i)=>{const start=from;from+=s.frames;return <Sequence key={i} from={start} durationInFrames={s.frames}><Chapter s={s} index={i}/><Audio src={staticFile(`authentic/voice-${i}.mp3`)}/>{i>0&&<Audio src={staticFile('pro/'+(['goal','brand'].includes(s.kind)?'sweep.wav':'tap.wav'))} volume={.23}/>}</Sequence>})}</AbsoluteFill>}
registerRoot(()=> <Composition id="BenCarsonPro" component={Film} width={1080} height={1920} fps={30} durationInFrames={scenes.reduce((n,s)=>n+s.frames,0)}/>);
