-- Añade únicamente las dos rondas de encéfalo al juego existente. Reejecutable.

begin;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values ('33da7371-8264-5a6c-a6b0-b81a63e38793','Encéfalo — Ronda 1: Organización y meninges (10 preguntas)','MORFOFUNCION','Residencia','espanol','publica','Ronda 1: diapositivas 2–14. Ronda 2: 15–26; la 27 es la portada de rombencéfalo.','ENCEFALO1',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Encéfalo: Organización y meninges','individual','{"maxQuestions":10,"questionOrder":["d9433d0c-5f19-5cd3-aa54-bced1909a690","cd70611a-4b2c-53c2-a0ed-6e77792705a1","b293f229-c3ae-50fa-af0f-b572ce3e2376","7b80b008-f068-5b7b-a574-01385492448e","aa00ada0-ff00-5559-aff1-6fca8ce90569","f9677388-622a-573f-acc2-b898d79510ed","6e74bcad-a602-5150-a6c7-9e7dafa0e23c","5224ba16-6bda-52da-a177-e2c2223ce7e0","24e55e1a-44ee-5b7f-a13b-9d8c1ce04f58","f8412c0f-0fa0-5a37-ae5c-09b6c1e5f757"],"enabledPowerups":["x2","time","retry"]}'::jsonb) on conflict(id) do update set titulo=excluded.titulo,tema=excluded.tema,objetivo=excluded.objetivo,publicado=true,iniciado=true,config_juego=excluded.config_juego,updated_at=now();

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d9433d0c-5f19-5cd3-aa54-bced1909a690','33da7371-8264-5a6c-a6b0-b81a63e38793','mc','¿Cuáles son las tres grandes porciones del encéfalo descritas en esta sección?','[{"text":"Cerebro, cerebelo y tallo encefálico","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s3-4.jpeg","explicacion":"El cerebro, el cerebelo y el tallo encefálico constituyen sus tres porciones principales."},{"text":"Cerebro, médula espinal y nervios","correct":false},{"text":"Tálamo, hipotálamo y ganglios","correct":false},{"text":"Duramadre, aracnoides y piamadre","correct":false}]'::jsonb,false,1,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('cd70611a-4b2c-53c2-a0ed-6e77792705a1','33da7371-8264-5a6c-a6b0-b81a63e38793','tf','El cerebelo contiene más de la mitad de las neuronas del encéfalo, aunque representa cerca del 10 % de su volumen.','[{"text":"Verdadero","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s3-4.jpeg","explicacion":"La proporción de neuronas no equivale a la proporción de volumen."},{"text":"Falso","correct":false}]'::jsonb,false,2,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('b293f229-c3ae-50fa-af0f-b572ce3e2376','33da7371-8264-5a6c-a6b0-b81a63e38793','ms','¿Qué elementos son característicos de la sustancia gris? Marca todas las respuestas correctas.','[{"text":"Cuerpos neuronales","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s3-4.jpeg","explicacion":"La sustancia gris reúne cuerpos neuronales, dendritas y sinapsis; la blanca está formada principalmente por haces de axones."},{"text":"Dendritas","correct":true},{"text":"Sinapsis","correct":true},{"text":"Haces de axones mielinizados como componente predominante","correct":false}]'::jsonb,true,3,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('7b80b008-f068-5b7b-a574-01385492448e','33da7371-8264-5a6c-a6b0-b81a63e38793','tf','En el encéfalo, toda la sustancia gris está en la superficie; no existen núcleos profundos.','[{"text":"Verdadero","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s3-4.jpeg","explicacion":"Además de la corteza superficial, existen núcleos profundos de sustancia gris rodeados por sustancia blanca."},{"text":"Falso","correct":true}]'::jsonb,false,4,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('aa00ada0-ff00-5559-aff1-6fca8ce90569','33da7371-8264-5a6c-a6b0-b81a63e38793','mc','¿Qué estructura embrionaria origina el encéfalo y la médula espinal?','[{"text":"Cresta neural","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s7-2.png","explicacion":"La placa neural se pliega y forma el tubo neural, precursor del sistema nervioso central."},{"text":"Notocordio","correct":false},{"text":"Tubo neural","correct":true},{"text":"Somita","correct":false}]'::jsonb,false,5,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('f9677388-622a-573f-acc2-b898d79510ed','33da7371-8264-5a6c-a6b0-b81a63e38793','match','Relaciona cada vesícula primaria con sus vesículas secundarias.','[{"text":"Prosencéfalo","match":"Telencéfalo y diencéfalo","pregunta_imagen":"/juegos/assets/encefalo/s9-4.png","explicacion":"El prosencéfalo se divide en dos vesículas, el mesencéfalo conserva su nombre y el rombencéfalo se divide en dos."},{"text":"Mesencéfalo","match":"Mesencéfalo"},{"text":"Rombencéfalo","match":"Metencéfalo y mielencéfalo"}]'::jsonb,false,6,1,90) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('6e74bcad-a602-5150-a6c7-9e7dafa0e23c','33da7371-8264-5a6c-a6b0-b81a63e38793','mc','¿Cuál es el orden de las meninges, desde el cráneo hacia el encéfalo?','[{"text":"Piamadre → aracnoides → duramadre","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s12-4.png","explicacion":"La duramadre es la más externa; la piamadre queda adherida al tejido nervioso."},{"text":"Duramadre → aracnoides → piamadre","correct":true},{"text":"Aracnoides → duramadre → piamadre","correct":false},{"text":"Duramadre → piamadre → aracnoides","correct":false}]'::jsonb,false,7,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('5224ba16-6bda-52da-a177-e2c2223ce7e0','33da7371-8264-5a6c-a6b0-b81a63e38793','ms','Selecciona las dos capas de la duramadre craneal.','[{"text":"Capa perióstica","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s12-4.png","explicacion":"La duramadre craneal posee una capa perióstica externa y una meníngea interna."},{"text":"Capa meníngea","correct":true},{"text":"Capa aracnoidea","correct":false},{"text":"Capa pial","correct":false}]'::jsonb,true,8,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('24e55e1a-44ee-5b7f-a13b-9d8c1ce04f58','33da7371-8264-5a6c-a6b0-b81a63e38793','match','Relaciona cada meninge con su característica principal.','[{"text":"Duramadre","match":"Membrana externa resistente","pregunta_imagen":"/juegos/assets/encefalo/s12-4.png","explicacion":"La piamadre sigue los contornos del encéfalo, incluso los surcos; el espacio subaracnoideo queda entre ella y la aracnoides."},{"text":"Aracnoides","match":"Membrana situada sobre el espacio subaracnoideo"},{"text":"Piamadre","match":"Membrana íntimamente adherida al encéfalo"}]'::jsonb,false,9,1,90) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('f8412c0f-0fa0-5a37-ae5c-09b6c1e5f757','33da7371-8264-5a6c-a6b0-b81a63e38793','mc','¿Entre qué meninges se encuentra el espacio subaracnoideo?','[{"text":"Duramadre y cráneo","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s12-4.png","explicacion":"El espacio subaracnoideo se sitúa entre la aracnoides y la piamadre y contiene líquido cefalorraquídeo."},{"text":"Duramadre y aracnoides","correct":false},{"text":"Aracnoides y piamadre","correct":true},{"text":"Piamadre y corteza cerebral","correct":false}]'::jsonb,false,10,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values ('2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','Encéfalo — Ronda 2: Ventrículos, LCR y barreras (10 preguntas)','MORFOFUNCION','Residencia','espanol','publica','Ronda 1: diapositivas 2–14. Ronda 2: 15–26; la 27 es la portada de rombencéfalo.','ENCEFALO2',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Encéfalo: Ventrículos, LCR y barreras','individual','{"maxQuestions":10,"questionOrder":["14d14f51-8785-53bb-a3c0-a4e4513d2570","48efdc83-79ac-5e40-aba5-0810360b047c","6198dee5-3795-52d4-abed-f76cd8d5917d","aa326b5e-7bc3-5676-aa01-4842b7afae37","b817fc21-c2aa-5223-a7d4-d4bfe0f2f51d","d4e58017-fe62-5b78-a15e-d67887e7f27f","f3df4df3-ccda-5d00-ad74-5fc39c2273ee","d8d7e798-7a13-5e2c-a775-79fd721cab23","af6b2e55-7c60-569e-acc9-177940fdadfa","5c7419e8-5838-519a-af69-b8640e15238f"],"enabledPowerups":["x2","time","retry"]}'::jsonb) on conflict(id) do update set titulo=excluded.titulo,tema=excluded.tema,objetivo=excluded.objetivo,publicado=true,iniciado=true,config_juego=excluded.config_juego,updated_at=now();

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('14d14f51-8785-53bb-a3c0-a4e4513d2570','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','mc','¿Cuántos ventrículos tiene el encéfalo?','[{"text":"Dos","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s15-2.png","explicacion":"Existen dos ventrículos laterales, un tercer ventrículo y un cuarto ventrículo."},{"text":"Tres","correct":false},{"text":"Cinco","correct":false},{"text":"Cuatro","correct":true}]'::jsonb,false,1,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('48efdc83-79ac-5e40-aba5-0810360b047c','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','match','Relaciona cada comunicación ventricular con las cavidades que conecta.','[{"text":"Agujeros interventriculares","match":"Ventrículos laterales → tercer ventrículo","pregunta_imagen":"/juegos/assets/encefalo/s15-2.png","explicacion":"El LCR pasa de los ventrículos laterales al tercero y, por el acueducto, al cuarto; sale al espacio subaracnoideo por las aberturas del cuarto ventrículo."},{"text":"Acueducto mesencefálico","match":"Tercer ventrículo → cuarto ventrículo"},{"text":"Aberturas mediana y laterales","match":"Cuarto ventrículo → espacio subaracnoideo"}]'::jsonb,false,2,1,90) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('6198dee5-3795-52d4-abed-f76cd8d5917d','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','tf','Los plexos coroideos participan en la producción de líquido cefalorraquídeo.','[{"text":"Verdadero","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s15-2.png","explicacion":"Los plexos coroideos, recubiertos por epitelio especializado, producen LCR."},{"text":"Falso","correct":false}]'::jsonb,false,3,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('aa326b5e-7bc3-5676-aa01-4842b7afae37','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','mc','Según la presentación, ¿cuánto LCR se produce aproximadamente cada día?','[{"text":"50 mL","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s18-2.png","explicacion":"La producción diaria es cercana a 500 mL; esto no equivale al volumen presente simultáneamente, que es menor."},{"text":"500 mL","correct":true},{"text":"1500 mL","correct":false},{"text":"5 mL","correct":false}]'::jsonb,false,4,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('b817fc21-c2aa-5223-a7d4-d4bfe0f2f51d','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','ms','¿Cuáles son funciones del líquido cefalorraquídeo?','[{"text":"Dar flotabilidad al encéfalo","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s18-2.png","explicacion":"El LCR permite flotación, amortigua movimientos y contribuye a la estabilidad química y eliminación de desechos."},{"text":"Amortiguar golpes y movimientos","correct":true},{"text":"Contribuir a la estabilidad química","correct":true},{"text":"Producir la mielina de los axones","correct":false}]'::jsonb,true,5,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d4e58017-fe62-5b78-a15e-d67887e7f27f','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','mc','¿Por qué estructuras retorna el LCR a la sangre venosa?','[{"text":"Plexos coroideos","correct":false,"pregunta_imagen":"/juegos/assets/encefalo/s18-2.png","explicacion":"Las granulaciones aracnoideas permiten la reabsorción del LCR hacia los senos venosos durales."},{"text":"Acueducto mesencefálico","correct":false},{"text":"Granulaciones aracnoideas","correct":true},{"text":"Raíces de los nervios espinales","correct":false}]'::jsonb,false,6,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('f3df4df3-ccda-5d00-ad74-5fc39c2273ee','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','tf','El encéfalo recibe aproximadamente el 15 % del flujo sanguíneo, aunque representa cerca del 2 % del peso corporal adulto.','[{"text":"Verdadero","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s25-1.png","explicacion":"Su elevada demanda metabólica explica que reciba una fracción importante del flujo sanguíneo."},{"text":"Falso","correct":false}]'::jsonb,false,7,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d8d7e798-7a13-5e2c-a775-79fd721cab23','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','mc','¿Cuál es la base estructural principal de la barrera hematoencefálica?','[{"text":"Uniones estrechas entre células endoteliales capilares","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s24-4.png","explicacion":"Las uniones estrechas entre células endoteliales de los capilares restringen el paso entre ellas; los astrocitos contribuyen a mantener la barrera."},{"text":"Separaciones amplias entre las células endoteliales","correct":false},{"text":"La capa perióstica de la duramadre","correct":false},{"text":"Las granulaciones aracnoideas","correct":false}]'::jsonb,false,8,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('af6b2e55-7c60-569e-acc9-177940fdadfa','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','ms','¿Qué afirmaciones sobre el sistema de barrera encefálica son correctas?','[{"text":"Permite el paso de oxígeno y dióxido de carbono","correct":true,"pregunta_imagen":"/juegos/assets/encefalo/s24-4.png","explicacion":"El oxígeno y el dióxido de carbono atraviesan con facilidad; la barrera es selectiva y puede dificultar la entrada de fármacos."},{"text":"Regula el intercambio entre sangre y tejido nervioso","correct":true},{"text":"Deja pasar por igual todas las sustancias","correct":false},{"text":"Puede dificultar la llegada de algunos medicamentos al encéfalo","correct":true}]'::jsonb,true,9,1,60) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('5c7419e8-5838-519a-af69-b8640e15238f','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2','match','Relaciona cada estructura con su papel en el LCR o en las barreras encefálicas.','[{"text":"Plexo coroideo","match":"Producción de LCR","pregunta_imagen":"/juegos/assets/encefalo/s25-1.png","explicacion":"Producción, reabsorción y control del intercambio son funciones diferentes."},{"text":"Granulación aracnoidea","match":"Reabsorción de LCR"},{"text":"Endotelio capilar con uniones estrechas","match":"Barrera hematoencefálica"}]'::jsonb,false,10,1,90) on conflict(id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

commit;

select e.titulo, count(p.id) as preguntas from public.evaluaciones e join public.evaluacion_preguntas p on p.evaluacion_id=e.id where e.id in ('33da7371-8264-5a6c-a6b0-b81a63e38793','2273cb7e-f0d5-594d-a3df-e1f5e9ba7ec2') group by e.id,e.titulo order by e.titulo;
