-- Tejido nervioso 2026: dos rondas independientes de 15 preguntas.
-- Fuente: TEJIDO NERVIOSO 2026 estudiantes--.pptx, hasta la primera diapositiva MIELINA (40).
-- Ejecutar completo en Supabase SQL Editor. No basta con subir el archivo a GitHub.
-- Conserva el formato y los comodines actuales de /juegos/. No modifica otros bancos.
-- Repetir la importación actualiza estas mismas preguntas, sin borrar resultados.

begin;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values (
'71c3ac1c-7bda-5eaa-a449-d0b94ac33684','Tejido nervioso — Ronda 1: organización y neuronas','MORFOFUNCION','Residencia','espanol','publica','Repasar el tejido nervioso hasta la introducción a la mielina mediante 15 preguntas.','NEURO26R1',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Tejido nervioso 2026: hasta mielina','test','{"maxQuestions": 15, "questionOrder": ["a1a0219f-e9e2-5790-8121-26f9842336a6", "51f2d419-e4c4-52e1-89cb-2b6bb08fdcbe", "a226f83f-9221-50b4-b7b8-57e12abdcf70", "8c3561db-13ac-5611-8352-ded754baf35e", "7e81bf5c-0d3c-5716-997c-04fee6a51ff3", "e09871cc-9dde-5dc2-94e9-d24801feb294", "a1a269bc-acea-5dd7-9bd4-1cf9c14358a8", "f5d2b4b9-7a4c-5eeb-a3fc-c0115b866da1", "305abaec-68d4-58b5-8dec-e076ab9cb4f6", "1a49630a-152e-5f64-9f64-0e5272e7d3c3", "141b561d-7c20-509b-84a4-2aa6eaa1865e", "d7d990b1-b5ae-580c-9d34-253c1ddba754", "883c4ce0-9cc3-53d1-9885-80f4622d92c9", "5f8d849a-6ed8-58be-a138-089f4206f1a9", "fc7858b5-2b6c-53ac-9a71-ff8831bda478"], "enabledPowerups": ["x2", "time", "hint", "retry"]}'::jsonb
) on conflict (id) do update set titulo=excluded.titulo, asignatura=excluded.asignatura, objetivo=excluded.objetivo, codigo=excluded.codigo, publicado=excluded.publicado, iniciado=excluded.iniciado, tema=excluded.tema, modo_sesion=excluded.modo_sesion, config_juego=excluded.config_juego, updated_at=now();

-- Ronda 1, pregunta 1. Diapositivas 2–5.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('a1a0219f-e9e2-5790-8121-26f9842336a6','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¡Ubica el centro de mando! ¿Qué estructuras forman el sistema nervioso central?',$$[{"text": "Encéfalo y médula espinal", "correct": true, "color": "ac-blue"}, {"text": "Nervios y ganglios", "correct": false, "color": "ac-green"}, {"text": "Encéfalo y nervios periféricos", "correct": false, "color": "ac-yellow"}, {"text": "Ganglios y médula espinal", "correct": false, "color": "ac-pink"}]$$::jsonb,false,1,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 2. Diapositivas 4–5.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('51f2d419-e4c4-52e1-89cb-2b6bb08fdcbe','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','ms','Selecciona los dos componentes del sistema nervioso periférico.',$$[{"text": "Encéfalo", "correct": false, "color": "ac-blue"}, {"text": "Nervios", "correct": true, "color": "ac-green"}, {"text": "Médula espinal", "correct": false, "color": "ac-yellow"}, {"text": "Ganglios", "correct": true, "color": "ac-pink"}]$$::jsonb,true,2,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 3. Diapositivas 2–4.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('a226f83f-9221-50b4-b7b8-57e12abdcf70','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','Detectas un cambio en el ambiente. ¿Qué secuencia resume la respuesta del sistema nervioso?',$$[{"text": "Respuesta motora, integración y detección", "correct": false, "color": "ac-blue"}, {"text": "Integración, respuesta motora y detección", "correct": false, "color": "ac-green"}, {"text": "Detección sensorial, integración y respuesta motora", "correct": true, "color": "ac-yellow"}, {"text": "Detección sensorial, respuesta motora e integración", "correct": false, "color": "ac-pink"}]$$::jsonb,false,3,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 4. Diapositivas 6–7.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('8c3561db-13ac-5611-8352-ded754baf35e','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','Una señal viaja desde un receptor hacia el SNC. ¿Por qué división circula?',$$[{"text": "Motora somática", "correct": false, "color": "ac-blue"}, {"text": "Motora visceral", "correct": false, "color": "ac-green"}, {"text": "Eferente", "correct": false, "color": "ac-yellow"}, {"text": "Sensorial o aferente", "correct": true, "color": "ac-pink"}]$$::jsonb,false,4,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 5. Diapositivas 7.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('7e81bf5c-0d3c-5716-997c-04fee6a51ff3','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','tf','Verdadero o falso: la división motora o eferente lleva señales desde el SNC hacia músculos y glándulas.',$$[{"text": "Verdadero", "correct": true, "color": "ac-blue"}, {"text": "Falso", "correct": false, "color": "ac-green"}]$$::jsonb,false,5,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 6. Diapositivas 6–7.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('e09871cc-9dde-5dc2-94e9-d24801feb294','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¿Cuál es un ejemplo de información sensorial visceral?',$$[{"text": "Señales de la piel", "correct": false, "color": "ac-blue"}, {"text": "Señales del estómago", "correct": true, "color": "ac-green"}, {"text": "Señales de las articulaciones", "correct": false, "color": "ac-yellow"}, {"text": "Señales de los músculos esqueléticos", "correct": false, "color": "ac-pink"}]$$::jsonb,false,6,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 7. Diapositivas 7–8.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('a1a269bc-acea-5dd7-9bd4-1cf9c14358a8','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','Levantas la mano para responder en clase. ¿Qué división lleva la orden al músculo esquelético?',$$[{"text": "Sensorial visceral", "correct": false, "color": "ac-blue"}, {"text": "Motora visceral", "correct": false, "color": "ac-green"}, {"text": "Motora somática", "correct": true, "color": "ac-yellow"}, {"text": "Sensorial somática", "correct": false, "color": "ac-pink"}]$$::jsonb,false,7,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 8. Diapositivas 8.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('f5d2b4b9-7a4c-5eeb-a3fc-c0115b866da1','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','ms','Selecciona las dos divisiones del sistema nervioso autónomo.',$$[{"text": "Central", "correct": false, "color": "ac-blue"}, {"text": "Somática", "correct": false, "color": "ac-green"}, {"text": "Simpática", "correct": true, "color": "ac-yellow"}, {"text": "Parasimpática", "correct": true, "color": "ac-pink"}]$$::jsonb,true,8,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 9. Diapositivas 8.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('305abaec-68d4-58b5-8dec-e076ab9cb4f6','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¡Suena la alarma! ¿Qué división prepara al organismo para actuar aumentando la frecuencia cardiaca?',$$[{"text": "Simpática", "correct": true, "color": "ac-blue"}, {"text": "Parasimpática", "correct": false, "color": "ac-green"}, {"text": "Sensorial somática", "correct": false, "color": "ac-yellow"}, {"text": "Sensorial visceral", "correct": false, "color": "ac-pink"}]$$::jsonb,false,9,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 10. Diapositivas 8.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('1a49630a-152e-5f64-9f64-0e5272e7d3c3','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','tf','Verdadero o falso: la división parasimpática estimula la digestión.',$$[{"text": "Verdadero", "correct": true, "color": "ac-blue"}, {"text": "Falso", "correct": false, "color": "ac-green"}]$$::jsonb,false,10,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 11. Diapositivas 10–12.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('141b561d-7c20-509b-84a4-2aa6eaa1865e','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¿Qué clase funcional de neurona detecta estímulos y lleva información hacia el SNC?',$$[{"text": "Motora", "correct": false, "color": "ac-blue"}, {"text": "Sensorial", "correct": true, "color": "ac-green"}, {"text": "Interneurona", "correct": false, "color": "ac-yellow"}, {"text": "Célula de Schwann", "correct": false, "color": "ac-pink"}]$$::jsonb,false,11,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 12. Diapositivas 10–12.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d7d990b1-b5ae-580c-9d34-253c1ddba754','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¿Dónde se encuentran las interneuronas según el esquema de clases funcionales?',$$[{"text": "Solo en los nervios periféricos", "correct": false, "color": "ac-blue"}, {"text": "Solo en los músculos", "correct": false, "color": "ac-green"}, {"text": "Dentro del SNC", "correct": true, "color": "ac-yellow"}, {"text": "En las glándulas", "correct": false, "color": "ac-pink"}]$$::jsonb,false,12,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 13. Diapositivas 14.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('883c4ce0-9cc3-53d1-9885-80f4622d92c9','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','mc','¿Cómo se llama el cuerpo celular de la neurona?',$$[{"text": "Axolema", "correct": false, "color": "ac-blue"}, {"text": "Dendrita", "correct": false, "color": "ac-green"}, {"text": "Botón sináptico", "correct": false, "color": "ac-yellow"}, {"text": "Soma o pericarion", "correct": true, "color": "ac-pink"}]$$::jsonb,false,13,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 14. Diapositivas 14.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('5f8d849a-6ed8-58be-a138-089f4206f1a9','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','ms','Selecciona las afirmaciones correctas sobre los cuerpos de Nissl.',$$[{"text": "Se relacionan con el retículo endoplasmático rugoso", "correct": true, "color": "ac-blue"}, {"text": "Se encuentran en el soma", "correct": true, "color": "ac-green"}, {"text": "Son vainas de mielina", "correct": false, "color": "ac-yellow"}, {"text": "Son los núcleos de las células de Schwann", "correct": false, "color": "ac-pink"}]$$::jsonb,true,14,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 1, pregunta 15. Diapositivas 16.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('fc7858b5-2b6c-53ac-9a71-ff8831bda478','71c3ac1c-7bda-5eaa-a449-d0b94ac33684','tf','Verdadero o falso: las dendritas suelen ser el principal sitio de recepción de señales de otras neuronas.',$$[{"text": "Verdadero", "correct": true, "color": "ac-blue"}, {"text": "Falso", "correct": false, "color": "ac-green"}]$$::jsonb,false,15,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values (
'243e1718-d7af-56bc-bf64-ea00346daa0d','Tejido nervioso — Ronda 2: neuroglía y mielina','MORFOFUNCION','Residencia','espanol','publica','Repasar el tejido nervioso hasta la introducción a la mielina mediante 15 preguntas.','NEURO26R2',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Tejido nervioso 2026: hasta mielina','test','{"maxQuestions": 15, "questionOrder": ["d52034d3-c792-5746-b036-da0ce8f42f24", "98094832-be1c-5ca1-ad91-8b4e15305e4f", "2da929a4-cd79-50e3-81a5-d23145e09f5d", "7b8b9f64-c847-57dc-9a9a-1bc60e5c77c3", "0fd4e183-6ec3-5836-a7cf-b8b294ccb356", "55f203d6-c8ee-5a77-ab9c-557d20f7e19b", "3178ada6-7dde-51a8-b0f9-222d88511752", "3a370012-42e8-5e2e-abd7-f592d756ad7b", "2377928d-7bb4-5142-b220-2754ce649a7f", "8d91c29f-ccf4-5b67-8d98-324853f3b388", "fab3b330-bd9c-5151-9fdb-88b6f5e50536", "9560acb7-11d6-5210-814b-9bc360c033f4", "23c84d42-a6ad-5129-b1da-53417c97f5f1", "9d794ddd-3368-5c9c-9471-ffd76ab96dc2", "d3b3e182-6629-53a8-9348-17ee12436cc5"], "enabledPowerups": ["x2", "time", "hint", "retry"]}'::jsonb
) on conflict (id) do update set titulo=excluded.titulo, asignatura=excluded.asignatura, objetivo=excluded.objetivo, codigo=excluded.codigo, publicado=excluded.publicado, iniciado=excluded.iniciado, tema=excluded.tema, modo_sesion=excluded.modo_sesion, config_juego=excluded.config_juego, updated_at=now();

-- Ronda 2, pregunta 1. Diapositivas 16–17.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d52034d3-c792-5746-b036-da0ce8f42f24','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','La señal debe viajar hacia otras células. ¿Qué prolongación neuronal está especializada en conducirla?',$$[{"text": "Dendrita", "correct": false, "color": "ac-blue"}, {"text": "Axón", "correct": true, "color": "ac-green"}, {"text": "Nucléolo", "correct": false, "color": "ac-yellow"}, {"text": "Cuerpo de Nissl", "correct": false, "color": "ac-pink"}]$$::jsonb,false,1,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 2. Diapositivas 17.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('98094832-be1c-5ca1-ad91-8b4e15305e4f','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Cómo se denomina la membrana plasmática del axón?',$$[{"text": "Axoplasma", "correct": false, "color": "ac-blue"}, {"text": "Neurilema", "correct": false, "color": "ac-green"}, {"text": "Axolema", "correct": true, "color": "ac-yellow"}, {"text": "Soma", "correct": false, "color": "ac-pink"}]$$::jsonb,false,2,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 3. Diapositivas 18–19.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('2da929a4-cd79-50e3-81a5-d23145e09f5d','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Qué contienen las vesículas de un botón sináptico?',$$[{"text": "Cuerpos de Nissl", "correct": false, "color": "ac-blue"}, {"text": "Núcleos de neuronas", "correct": false, "color": "ac-green"}, {"text": "Capas de mielina", "correct": false, "color": "ac-yellow"}, {"text": "Neurotransmisores", "correct": true, "color": "ac-pink"}]$$::jsonb,false,3,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 4. Diapositivas 20–27.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('7b8b9f64-c847-57dc-9a9a-1bc60e5c77c3','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','Una neurona tiene un axón y varias dendritas. ¿Cómo se clasifica por su estructura?',$$[{"text": "Multipolar", "correct": true, "color": "ac-blue"}, {"text": "Bipolar", "correct": false, "color": "ac-green"}, {"text": "Unipolar", "correct": false, "color": "ac-yellow"}, {"text": "Anaxónica", "correct": false, "color": "ac-pink"}]$$::jsonb,false,4,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 5. Diapositivas 20–27.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('0fd4e183-6ec3-5836-a7cf-b8b294ccb356','243e1718-d7af-56bc-bf64-ea00346daa0d','tf','Verdadero o falso: una neurona bipolar tiene un axón y una dendrita que salen del soma.',$$[{"text": "Verdadero", "correct": true, "color": "ac-blue"}, {"text": "Falso", "correct": false, "color": "ac-green"}]$$::jsonb,false,5,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 6. Diapositivas 28.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('55f203d6-c8ee-5a77-ab9c-557d20f7e19b','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','Un paquete sale del soma y avanza por el axón. ¿Qué transporte está realizando?',$$[{"text": "Retrógrado", "correct": false, "color": "ac-blue"}, {"text": "Anterógrado", "correct": true, "color": "ac-green"}, {"text": "Exclusivamente dendrítico", "correct": false, "color": "ac-yellow"}, {"text": "Desde el axón hacia el soma", "correct": false, "color": "ac-pink"}]$$::jsonb,false,6,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 7. Diapositivas 28–30.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('3178ada6-7dde-51a8-b0f9-222d88511752','243e1718-d7af-56bc-bf64-ea00346daa0d','ms','Selecciona las asociaciones correctas del transporte axonal.',$$[{"text": "Anterógrado: desde el soma hacia el axón", "correct": true, "color": "ac-blue"}, {"text": "Retrógrado: desde el axón hacia el soma", "correct": true, "color": "ac-green"}, {"text": "Anterógrado: siempre hacia el soma", "correct": false, "color": "ac-yellow"}, {"text": "Retrógrado: siempre se aleja del soma", "correct": false, "color": "ac-pink"}]$$::jsonb,true,7,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 8. Diapositivas 32.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('3a370012-42e8-5e2e-abd7-f592d756ad7b','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Qué célula produce mielina en el sistema nervioso central?',$$[{"text": "Célula satélite", "correct": false, "color": "ac-blue"}, {"text": "Microglía", "correct": false, "color": "ac-green"}, {"text": "Oligodendrocito", "correct": true, "color": "ac-yellow"}, {"text": "Célula ependimaria", "correct": false, "color": "ac-pink"}]$$::jsonb,false,8,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 9. Diapositivas 32–34.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('2377928d-7bb4-5142-b220-2754ce649a7f','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Qué células revisten las cavidades internas del encéfalo y el conducto central de la médula espinal?',$$[{"text": "Células de Schwann", "correct": false, "color": "ac-blue"}, {"text": "Células satélite", "correct": false, "color": "ac-green"}, {"text": "Oligodendrocitos", "correct": false, "color": "ac-yellow"}, {"text": "Células ependimarias", "correct": true, "color": "ac-pink"}]$$::jsonb,false,9,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 10. Diapositivas 33–34.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('8d91c29f-ccf4-5b67-8d98-324853f3b388','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¡Equipo de limpieza! ¿Qué células retiran microorganismos y restos celulares por fagocitosis en el SNC?',$$[{"text": "Microglía", "correct": true, "color": "ac-blue"}, {"text": "Astrocitos", "correct": false, "color": "ac-green"}, {"text": "Células satélite", "correct": false, "color": "ac-yellow"}, {"text": "Células de Schwann", "correct": false, "color": "ac-pink"}]$$::jsonb,false,10,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 11. Diapositivas 35–36.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('fab3b330-bd9c-5151-9fdb-88b6f5e50536','243e1718-d7af-56bc-bf64-ea00346daa0d','ms','Selecciona dos funciones de los astrocitos.',$$[{"text": "Formar toda la mielina periférica", "correct": false, "color": "ac-blue"}, {"text": "Ayudar a mantener la barrera hematoencefálica", "correct": true, "color": "ac-green"}, {"text": "Regular la composición química del líquido tisular", "correct": true, "color": "ac-yellow"}, {"text": "Revestir los somas de los ganglios periféricos", "correct": false, "color": "ac-pink"}]$$::jsonb,true,11,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 12. Diapositivas 37.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('9560acb7-11d6-5210-814b-9bc360c033f4','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Qué células rodean los somas neuronales de los ganglios del SNP y regulan su entorno?',$$[{"text": "Microglía", "correct": false, "color": "ac-blue"}, {"text": "Células ependimarias", "correct": false, "color": "ac-green"}, {"text": "Células satélite", "correct": true, "color": "ac-yellow"}, {"text": "Oligodendrocitos", "correct": false, "color": "ac-pink"}]$$::jsonb,false,12,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 13. Diapositivas 37–40.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('23c84d42-a6ad-5129-b1da-53417c97f5f1','243e1718-d7af-56bc-bf64-ea00346daa0d','tf','Verdadero o falso: las células de Schwann producen la mielina del sistema nervioso central.',$$[{"text": "Verdadero", "correct": false, "color": "ac-blue"}, {"text": "Falso", "correct": true, "color": "ac-green"}]$$::jsonb,false,13,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 14. Diapositivas 40.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('9d794ddd-3368-5c9c-9471-ffd76ab96dc2','243e1718-d7af-56bc-bf64-ea00346daa0d','mc','¿Qué describe mejor la vaina de mielina?',$$[{"text": "Una agrupación de somas en un ganglio", "correct": false, "color": "ac-blue"}, {"text": "Una prolongación que recibe señales", "correct": false, "color": "ac-green"}, {"text": "El núcleo de una neurona", "correct": false, "color": "ac-yellow"}, {"text": "Una cubierta aislante alrededor de una fibra nerviosa", "correct": true, "color": "ac-pink"}]$$::jsonb,false,14,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Ronda 2, pregunta 15. Diapositivas 40.
insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d3b3e182-6629-53a8-9348-17ee12436cc5','243e1718-d7af-56bc-bf64-ea00346daa0d','ms','Reto final: selecciona las afirmaciones correctas sobre la mielina.',$$[{"text": "Tiene un alto contenido de lípidos", "correct": true, "color": "ac-blue"}, {"text": "La producen oligodendrocitos en el SNC", "correct": true, "color": "ac-green"}, {"text": "La producen células de Schwann en el SNP", "correct": true, "color": "ac-yellow"}, {"text": "Está compuesta únicamente por proteínas", "correct": false, "color": "ac-pink"}]$$::jsonb,true,15,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

commit;

-- Verificación: cada ronda debe tener 15 preguntas y límite 15.
select e.titulo, count(p.id) as preguntas, e.config_juego->>'maxQuestions' as limite
from public.evaluaciones e join public.evaluacion_preguntas p on p.evaluacion_id=e.id
where e.id in ('71c3ac1c-7bda-5eaa-a449-d0b94ac33684','243e1718-d7af-56bc-bf64-ea00346daa0d')
group by e.id, e.titulo, e.config_juego order by e.titulo;
