-- Jhuly: 20 preguntas, 10 fáciles y 10 intermedias. Fuente: diapos. 51-117.

-- Sin memoria ni Alzheimer/Parkinson. Conserva las otras rondas y resultados.

begin;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values ('b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','Tejido nervioso — Electricidad, sinapsis y circuitos (20 preguntas)','MORFOFUNCION','Residencia','espanol','publica','Repasar el contenido de electricidad neuronal, sinapsis, integración y circuitos de las diapositivas de Jhuly.','NEUROJH20',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Tejido nervioso: electricidad, sinapsis y circuitos','test','{"maxQuestions": 20, "questionOrder": ["13feb955-78dd-517b-b546-d2109dcccf87", "ee3f5533-691c-59fc-8c9b-bae4ab19f460", "662f2b63-8e62-5aad-9b6c-23c379374bb2", "2c13905e-e279-5f63-9e8c-46495150c5ca", "46edae80-8fa8-5be9-ae5d-dad15609a8d8", "22b56a51-e1c6-5345-ac69-a2fbe6b5e464", "93a510a0-4257-5994-b1ec-1a7ebec5828b", "881cd4b9-0e76-53d3-b63c-9e78a16c8ec3", "26db9948-dc42-5d03-8f18-8eac1612efc7", "117828c1-2a48-5389-8437-181bf29d1e85", "6237c5ce-bed7-529e-82ac-edbf76c2a0ff", "ca891225-335f-56b9-abdd-681415867d0e", "543a6b23-f608-55c8-b0a3-d894655b4aa2", "120f8156-9850-514f-98ba-d07faa7c97cb", "da990b70-6c3a-548f-92c6-758f2d5751ad", "85e9a61a-c3c4-5a88-a365-c8d4761a55b3", "41ef5c48-1518-51df-8701-6c8af654bb61", "cdd0c6d8-87a8-50db-8b5b-7a9732c5cfcf", "5361775b-8fcd-5cb0-b3fb-724cd3f5bb64", "1c46378b-911f-5872-9676-289d426a7cda"], "enabledPowerups": ["x2", "time", "hint", "retry"]}'::jsonb) on conflict (id) do update set titulo=excluded.titulo,asignatura=excluded.asignatura,objetivo=excluded.objetivo,publicado=excluded.publicado,iniciado=excluded.iniciado,tema=excluded.tema,modo_sesion=excluded.modo_sesion,config_juego=excluded.config_juego,updated_at=now();

-- 1. Nivel fácil. Diapositiva 51.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('13feb955-78dd-517b-b546-d2109dcccf87','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué es una corriente eléctrica?','[{"text": "Una diferencia de temperatura", "correct": false, "color": "ac-blue"}, {"text": "Un flujo de partículas cargadas", "correct": true, "color": "ac-green"}, {"text": "Una capa de mielina", "correct": false, "color": "ac-yellow"}, {"text": "Una unión entre células", "correct": false, "color": "ac-pink"}]'::jsonb,false,1,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 2. Nivel fácil. Diapositiva 53.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('ee3f5533-691c-59fc-8c9b-bae4ab19f460','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','En reposo, ¿cómo es el interior de la neurona respecto al exterior?','[{"text": "Más negativo", "correct": true, "color": "ac-blue"}, {"text": "Más positivo", "correct": false, "color": "ac-green"}, {"text": "Siempre igual", "correct": false, "color": "ac-yellow"}, {"text": "Sin cargas eléctricas", "correct": false, "color": "ac-pink"}]'::jsonb,false,2,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 3. Nivel intermedio. Diapositiva 53.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('662f2b63-8e62-5aad-9b6c-23c379374bb2','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué hace la bomba de sodio y potasio en cada ciclo?','[{"text": "Introduce 3 Na⁺ y expulsa 2 K⁺", "correct": false, "color": "ac-blue"}, {"text": "Expulsa 2 Na⁺ e introduce 3 K⁺", "correct": false, "color": "ac-green"}, {"text": "Expulsa 3 Na⁺ e introduce 2 K⁺", "correct": true, "color": "ac-yellow"}, {"text": "Introduce Na⁺ y K⁺ en igual cantidad", "correct": false, "color": "ac-pink"}]'::jsonb,false,3,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 4. Nivel intermedio. Diapositiva 56.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('2c13905e-e279-5f63-9e8c-46495150c5ca','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','El interior de la neurona es negativo. ¿Qué efecto eléctrico ejerce sobre el K⁺?','[{"text": "Lo repele hacia fuera", "correct": false, "color": "ac-blue"}, {"text": "No ejerce ningún efecto", "correct": false, "color": "ac-green"}, {"text": "Lo convierte en Na⁺", "correct": false, "color": "ac-yellow"}, {"text": "Lo atrae hacia el interior", "correct": true, "color": "ac-pink"}]'::jsonb,false,4,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 5. Nivel fácil. Diapositiva 61.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('46edae80-8fa8-5be9-ae5d-dad15609a8d8','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Los potenciales locales son graduados. ¿Qué significa?','[{"text": "Su amplitud varía con la fuerza del estímulo", "correct": true, "color": "ac-blue"}, {"text": "Siempre tienen la misma amplitud", "correct": false, "color": "ac-green"}, {"text": "No cambian con los estímulos", "correct": false, "color": "ac-yellow"}, {"text": "Solo aparecen en la mielina", "correct": false, "color": "ac-pink"}]'::jsonb,false,5,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 6. Nivel intermedio. Diapositiva 61.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('22b56a51-e1c6-5345-ac69-a2fbe6b5e464','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Un potencial local se debilita al alejarse de su origen. ¿Qué propiedad muestra?','[{"text": "Todo o nada", "correct": false, "color": "ac-blue"}, {"text": "Decremental", "correct": true, "color": "ac-green"}, {"text": "Irreversible", "correct": false, "color": "ac-yellow"}, {"text": "Refractaria", "correct": false, "color": "ac-pink"}]'::jsonb,false,6,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 7. Nivel intermedio. Diapositiva 63.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('93a510a0-4257-5994-b1ec-1a7ebec5828b','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Un potencial local llega a la zona de activación, pero no alcanza el umbral. ¿Qué ocurre?','[{"text": "Se libera siempre neurotransmisor", "correct": false, "color": "ac-blue"}, {"text": "Se produce un potencial de acción mayor", "correct": false, "color": "ac-green"}, {"text": "No se desencadena un potencial de acción", "correct": true, "color": "ac-yellow"}, {"text": "Se elimina el periodo refractario", "correct": false, "color": "ac-pink"}]'::jsonb,false,7,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 8. Nivel fácil. Diapositiva 63.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('881cd4b9-0e76-53d3-b63c-9e78a16c8ec3','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Durante la repolarización descrita en las diapositivas, ¿qué ion sale de la célula?','[{"text": "Calcio", "correct": false, "color": "ac-blue"}, {"text": "Sodio", "correct": false, "color": "ac-green"}, {"text": "Cloruro", "correct": false, "color": "ac-yellow"}, {"text": "Potasio", "correct": true, "color": "ac-pink"}]'::jsonb,false,8,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 9. Nivel intermedio. Diapositiva 69.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('26db9948-dc42-5d03-8f18-8eac1612efc7','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Durante el periodo refractario absoluto, ¿puede un estímulo muy intenso provocar otro potencial de acción en esa región?','[{"text": "Sí, siempre", "correct": false, "color": "ac-blue"}, {"text": "No, ningún estímulo lo provoca en ese periodo", "correct": true, "color": "ac-green"}, {"text": "Solo si la fibra tiene mielina", "correct": false, "color": "ac-yellow"}, {"text": "Solo si entra neurotransmisor", "correct": false, "color": "ac-pink"}]'::jsonb,false,9,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 10. Nivel fácil. Diapositiva 77.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('117828c1-2a48-5389-8437-181bf29d1e85','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Cómo se llama la conducción característica de las fibras mielinizadas?','[{"text": "Saltatoria", "correct": true, "color": "ac-blue"}, {"text": "Continua", "correct": false, "color": "ac-green"}, {"text": "Decremental", "correct": false, "color": "ac-yellow"}, {"text": "Reverberante", "correct": false, "color": "ac-pink"}]'::jsonb,false,10,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 11. Nivel fácil. Diapositiva 80.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('6237c5ce-bed7-529e-82ac-edbf76c2a0ff','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué contienen las vesículas sinápticas?','[{"text": "Nodos de Ranvier", "correct": false, "color": "ac-blue"}, {"text": "Vainas de mielina", "correct": false, "color": "ac-green"}, {"text": "Neurotransmisores", "correct": true, "color": "ac-yellow"}, {"text": "Cuerpos neuronales", "correct": false, "color": "ac-pink"}]'::jsonb,false,11,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 12. Nivel fácil. Diapositiva 87.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('ca891225-335f-56b9-abdd-681415867d0e','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué ion entra en el botón presináptico y favorece la liberación del neurotransmisor?','[{"text": "Cloruro", "correct": false, "color": "ac-blue"}, {"text": "Potasio", "correct": false, "color": "ac-green"}, {"text": "Magnesio", "correct": false, "color": "ac-yellow"}, {"text": "Calcio", "correct": true, "color": "ac-pink"}]'::jsonb,false,12,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 13. Nivel fácil. Diapositiva 89.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('543a6b23-f608-55c8-b0a3-d894655b4aa2','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué neurotransmisor participa en la sinapsis inhibitoria GABAérgica?','[{"text": "GABA", "correct": true, "color": "ac-blue"}, {"text": "Acetilcolina", "correct": false, "color": "ac-green"}, {"text": "Noradrenalina", "correct": false, "color": "ac-yellow"}, {"text": "Glutamato", "correct": false, "color": "ac-pink"}]'::jsonb,false,13,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 14. Nivel intermedio. Diapositiva 94.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('120f8156-9850-514f-98ba-d07faa7c97cb','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Por qué debe retirarse el estímulo químico de la sinapsis en el momento adecuado?','[{"text": "Para producir mielina", "correct": false, "color": "ac-blue"}, {"text": "Para evitar una activación postsináptica indefinida", "correct": true, "color": "ac-green"}, {"text": "Para eliminar todos los receptores", "correct": false, "color": "ac-yellow"}, {"text": "Para transformar el axón en dendrita", "correct": false, "color": "ac-pink"}]'::jsonb,false,14,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 15. Nivel fácil. Diapositiva 109.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('da990b70-6c3a-548f-92c6-758f2d5751ad','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','¿Qué efecto tiene un potencial excitatorio postsináptico (PEPS)?','[{"text": "Forma una vaina de mielina", "correct": false, "color": "ac-blue"}, {"text": "Siempre impide llegar al umbral", "correct": false, "color": "ac-green"}, {"text": "Favorece alcanzar el umbral", "correct": true, "color": "ac-yellow"}, {"text": "Destruye los neurotransmisores", "correct": false, "color": "ac-pink"}]'::jsonb,false,15,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 16. Nivel intermedio. Diapositiva 109.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('85e9a61a-c3c4-5a88-a365-c8d4761a55b3','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Llegan señales muy próximas en el tiempo a través de la misma sinapsis. ¿Qué tipo de sumación ocurre?','[{"text": "Espacial", "correct": false, "color": "ac-blue"}, {"text": "Saltatoria", "correct": false, "color": "ac-green"}, {"text": "Refractaria", "correct": false, "color": "ac-yellow"}, {"text": "Temporal", "correct": true, "color": "ac-pink"}]'::jsonb,false,16,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 17. Nivel intermedio. Diapositiva 109.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('41ef5c48-1518-51df-8701-6c8af654bb61','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Varias sinapsis aportan señales al mismo tiempo a una neurona. ¿Qué tipo de sumación ocurre?','[{"text": "Espacial", "correct": true, "color": "ac-blue"}, {"text": "Temporal", "correct": false, "color": "ac-green"}, {"text": "Axonal", "correct": false, "color": "ac-yellow"}, {"text": "Refractaria", "correct": false, "color": "ac-pink"}]'::jsonb,false,17,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 18. Nivel intermedio. Diapositiva 110.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('cdd0c6d8-87a8-50db-8b5b-7a9732c5cfcf','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Un estímulo más fuerte activa neuronas adicionales. ¿Cómo se llama ese proceso?','[{"text": "Repolarización", "correct": false, "color": "ac-blue"}, {"text": "Reclutamiento", "correct": true, "color": "ac-green"}, {"text": "Reverberación", "correct": false, "color": "ac-yellow"}, {"text": "Hiperpolarización", "correct": false, "color": "ac-pink"}]'::jsonb,false,18,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 19. Nivel fácil. Diapositiva 113.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('5361775b-8fcd-5cb0-b3fb-724cd3f5bb64','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','En un circuito divergente, ¿hacia dónde se distribuye la información?','[{"text": "De muchas neuronas a una sola", "correct": false, "color": "ac-blue"}, {"text": "Solo hacia la misma neurona", "correct": false, "color": "ac-green"}, {"text": "De una vía hacia varias células postsinápticas", "correct": true, "color": "ac-yellow"}, {"text": "Exclusivamente hacia una glándula", "correct": false, "color": "ac-pink"}]'::jsonb,false,19,1,45) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- 20. Nivel intermedio. Diapositiva 113.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('1c46378b-911f-5872-9676-289d426a7cda','b1fe4fa3-5825-5d93-98a3-3c7a669d3f95','mc','Varias fibras nerviosas llevan información hacia una neurona o conjunto neural. ¿Qué circuito representa?','[{"text": "Divergente", "correct": false, "color": "ac-blue"}, {"text": "Reverberante", "correct": false, "color": "ac-green"}, {"text": "Paralelo después de la descarga", "correct": false, "color": "ac-yellow"}, {"text": "Convergente", "correct": true, "color": "ac-pink"}]'::jsonb,false,20,1,60) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

do $$ begin if (select count(*) from public.evaluacion_preguntas where evaluacion_id='b1fe4fa3-5825-5d93-98a3-3c7a669d3f95') <> 20 then raise exception 'Se requieren exactamente 20 preguntas'; end if; end $$;

commit;
