-- AlcocerMed. Fuente: TEJIDO NERVIOSO 2026 estudiantes.pptx, diapositivas 41–50.

-- La diapositiva 50 es una portada. Las preguntas evalúan el contenido de 41–49.

-- Ejecutar completo en Supabase SQL Editor. Subir a GitHub NO importa la evaluación.

-- No altera las dos primeras rondas ni elimina resultados. Importación idempotente.

begin;

insert into public.evaluaciones (id,titulo,asignatura,nivel,idioma,visibilidad,objetivo,codigo,publicado,created_by,created_at,updated_at,iniciado,tema,modo_sesion,config_juego) values ('2faa1933-85fe-57d4-b660-850984685824','Tejido nervioso — Ronda 3: diapositivas 41 a 50','MORFOFUNCION','Residencia','espanol','publica','Repasar mielina, conducción y regeneración periférica en 10 preguntas.','NEURO26R3',true,'dd2eed5d-b917-4c4d-b0e7-aa6b1e57ef23',now(),now(),true,'Tejido nervioso 2026: diapositivas 41–50','test','{"maxQuestions": 10, "questionOrder": ["2e7f0db0-1b1b-550c-943e-1f296c6d04bd", "da8147d8-4f1e-560a-961a-db4e5b197b63", "d4745aea-c22a-5a39-ae18-d9b9388fb28e", "23670aca-2d3f-54e8-9616-bc66ce6035df", "e91f3b8b-5565-5c51-8ea4-e47ebd9aa665", "8e3bf1b0-0b57-58f4-8e27-1cbe120ed2da", "22b6ab49-b24c-5f18-b841-f939825f1301", "ee79a6c8-fa12-55f6-a720-161a2e69d09b", "cb5e7921-c99f-5922-9251-0e9c9779a466", "407eba9b-0ef8-559d-9caf-39afc8228624"], "enabledPowerups": ["x2", "time", "hint", "retry"]}'::jsonb) on conflict (id) do update set titulo=excluded.titulo,asignatura=excluded.asignatura,objetivo=excluded.objetivo,codigo=excluded.codigo,publicado=excluded.publicado,iniciado=excluded.iniciado,tema=excluded.tema,modo_sesion=excluded.modo_sesion,config_juego=excluded.config_juego,updated_at=now();

-- Pregunta 1. Diapositiva 41.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('2e7f0db0-1b1b-550c-943e-1f296c6d04bd','2faa1933-85fe-57d4-b660-850984685824','mc','En una fibra mielinizada, ¿cómo se llaman las interrupciones entre segmentos de mielina?','[{"text": "Botones sinápticos", "correct": false, "color": "ac-blue"}, {"text": "Nodos de Ranvier", "correct": true, "color": "ac-green"}, {"text": "Cuerpos de Nissl", "correct": false, "color": "ac-yellow"}, {"text": "Dendritas", "correct": false, "color": "ac-pink"}]'::jsonb,false,1,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 2. Diapositiva 41.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('da8147d8-4f1e-560a-961a-db4e5b197b63','2faa1933-85fe-57d4-b660-850984685824','mc','¿Qué diferencia a la mielinización del SNC de la del SNP?','[{"text": "La microglía forma mielina en ambos sistemas", "correct": false, "color": "ac-blue"}, {"text": "Cada célula de Schwann mieliniza varios axones del SNC", "correct": false, "color": "ac-green"}, {"text": "Un oligodendrocito puede mielinizar segmentos de varios axones; una célula de Schwann forma un segmento en un axón del SNP", "correct": true, "color": "ac-yellow"}, {"text": "La mielina solo se encuentra en el SNP", "correct": false, "color": "ac-pink"}]'::jsonb,false,2,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 3. Diapositiva 42.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('d4745aea-c22a-5a39-ae18-d9b9388fb28e','2faa1933-85fe-57d4-b660-850984685824','mc','La esclerosis múltiple daña la mielina del SNC. ¿Qué consecuencia funcional se relaciona con ese daño?','[{"text": "La conducción nerviosa puede hacerse más lenta o interrumpirse", "correct": true, "color": "ac-blue"}, {"text": "Todos los axones conducen más rápido", "correct": false, "color": "ac-green"}, {"text": "La fibra se convierte en una célula muscular", "correct": false, "color": "ac-yellow"}, {"text": "Aumenta obligatoriamente el diámetro de todas las fibras", "correct": false, "color": "ac-pink"}]'::jsonb,false,3,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 4. Diapositiva 43.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('23670aca-2d3f-54e8-9616-bc66ce6035df','2faa1933-85fe-57d4-b660-850984685824','mc','¿Qué característica corresponde a la enfermedad de Tay-Sachs presentada en clase?','[{"text": "Se produce por una sección traumática del nervio", "correct": false, "color": "ac-blue"}, {"text": "Es un aumento normal de mielina durante el desarrollo", "correct": false, "color": "ac-green"}, {"text": "Afecta exclusivamente a los músculos", "correct": false, "color": "ac-yellow"}, {"text": "Es hereditaria y se relaciona con una deficiencia enzimática que causa acumulación de lípidos en las neuronas", "correct": true, "color": "ac-pink"}]'::jsonb,false,4,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 5. Diapositiva 44.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('e91f3b8b-5565-5c51-8ea4-e47ebd9aa665','2faa1933-85fe-57d4-b660-850984685824','tf','Una fibra amielínica del SNP puede estar alojada en una célula de Schwann aunque no tenga una vaina de mielina.','[{"text": "Verdadero", "correct": true, "color": "ac-blue"}, {"text": "Falso", "correct": false, "color": "ac-green"}]'::jsonb,false,5,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 6. Diapositiva 45.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('8e3bf1b0-0b57-58f4-8e27-1cbe120ed2da','2faa1933-85fe-57d4-b660-850984685824','ms','Selecciona los DOS factores que favorecen una conducción nerviosa más rápida.','[{"text": "Mayor diámetro de la fibra", "correct": true, "color": "ac-blue"}, {"text": "Ausencia de mielina", "correct": false, "color": "ac-green"}, {"text": "Presencia de mielina", "correct": true, "color": "ac-yellow"}, {"text": "Menor diámetro de la fibra", "correct": false, "color": "ac-pink"}]'::jsonb,true,6,1,50) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 7. Diapositiva 46.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('22b6ab49-b24c-5f18-b841-f939825f1301','2faa1933-85fe-57d4-b660-850984685824','mc','Tras una lesión de una fibra nerviosa periférica, ¿qué situación permite que exista posibilidad de regeneración?','[{"text": "La desaparición completa del soma", "correct": false, "color": "ac-blue"}, {"text": "Un soma intacto y conservación de parte del neurilema", "correct": true, "color": "ac-green"}, {"text": "La destrucción de todo el trayecto de soporte", "correct": false, "color": "ac-yellow"}, {"text": "La conversión del axón en una dendrita", "correct": false, "color": "ac-pink"}]'::jsonb,false,7,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 8. Diapositiva 47.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('ee79a6c8-fa12-55f6-a720-161a2e69d09b','2faa1933-85fe-57d4-b660-850984685824','mc','Un músculo pierde su inervación después de una lesión nerviosa. ¿Qué cambio se describe en las diapositivas?','[{"text": "Aumenta su volumen sin actividad nerviosa", "correct": false, "color": "ac-blue"}, {"text": "Se transforma en tejido nervioso", "correct": false, "color": "ac-green"}, {"text": "Se contrae de forma permanente por producir mielina", "correct": false, "color": "ac-yellow"}, {"text": "Sus fibras se encogen: atrofia por desnervación", "correct": true, "color": "ac-pink"}]'::jsonb,false,8,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 9. Diapositiva 48.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('cb5e7921-c99f-5922-9251-0e9c9779a466','2faa1933-85fe-57d4-b660-850984685824','mc','Durante la regeneración de un nervio periférico, ¿qué guía el brote axonal hacia su destino?','[{"text": "Un nuevo oligodendrocito que sale del encéfalo", "correct": false, "color": "ac-blue"}, {"text": "La vaina de mielina de otra neurona del SNC", "correct": false, "color": "ac-green"}, {"text": "El conducto de regeneración formado por células de Schwann, lámina basal y neurilema", "correct": true, "color": "ac-yellow"}, {"text": "La desaparición de todas las células de Schwann", "correct": false, "color": "ac-pink"}]'::jsonb,false,9,1,40) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

-- Pregunta 10. Diapositiva 49.

insert into public.evaluacion_preguntas (id,evaluacion_id,tipo,texto,opciones,multiple_correctas,orden,puntos,temporizador) values ('407eba9b-0ef8-559d-9caf-39afc8228624','2faa1933-85fe-57d4-b660-850984685824','tf','La regeneración de una fibra nerviosa periférica garantiza siempre la recuperación completa de su función.','[{"text": "Verdadero", "correct": false, "color": "ac-blue"}, {"text": "Falso", "correct": true, "color": "ac-green"}]'::jsonb,false,10,1,30) on conflict (id) do update set tipo=excluded.tipo,texto=excluded.texto,opciones=excluded.opciones,multiple_correctas=excluded.multiple_correctas,orden=excluded.orden,puntos=excluded.puntos,temporizador=excluded.temporizador;

do $$ begin if (select count(*) from public.evaluacion_preguntas where evaluacion_id='2faa1933-85fe-57d4-b660-850984685824') <> 10 then raise exception 'La ronda debe tener exactamente 10 preguntas'; end if; end $$;

commit;
